@startuml UndoState1
!include ../style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 5"

package "Current State" {
    class CurrentAB as "<u>ab1:AddressBook</u>"
    class CurrentTS as "<u>ts0:Timeslots</u>"
}

package "Previous State (SAVED)" #FFDDDD {
    class PreviousAB as "<u>ab0:AddressBook</u>"
    class PreviousTS as "<u>ts0:Timeslots</u>"
}

note bottom of PreviousAB
  Before deleting the 5th student
  Previous state saved
  Can undo
end note

note bottom of CurrentAB
  After deleting the 5th student
end note

@end
